#!/bin/bash

youtube-dl -q -o - "$1" | \
ffmpeg -re -i - -c copy -preset ultrafast -tune zerolatency -maxrate 10000k -bufsize 20000k -g 60 -f mp4 -movflags frag_keyframe+faststart -max_muxing_queue_size 9999 -listen 1 http://0.0.0.0:5000/stream
# ffmpeg -re -i - -c copy -maxrate 10000k -bufsize 20000k -f mp4 -movflags frag_keyframe+faststart -max_muxing_queue_size 9999 -listen 1 http://0.0.0.0:5000/stream
